[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
